# Generated by Django 5.2 on 2025-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_dailytimeallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytimeallocation',
            old_name='break_minutes_used',
            new_name='break1_minutes_used',
        ),
        migrations.RenameField(
            model_name='dailytimeallocation',
            old_name='break_start_time',
            new_name='break1_start_time',
        ),
        migrations.AddField(
            model_name='dailytimeallocation',
            name='break2_minutes_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytimeallocation',
            name='break2_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
